import {
  faArrowLeft,
  faArrowRight,
  faBan,
  faCheck,
  faChevronDown,
  faChevronRight,
  faClock,
  faClockRotateLeft,
  faComment,
  faCopy,
  faCrown,
  faDoorOpen,
  faDroplet,
  faEnvelope,
  faExclamation,
  faEye,
  faEyeSlash,
  faFaceSmile,
  faFire,
  faFlag,
  faGamepad,
  faGear,
  faHouse,
  faKey,
  faLightbulb,
  faLinkSlash,
  faLock,
  faMagnifyingGlass,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faMinus,
  faPaperPlane,
  faPeopleGroup,
  faPlay,
  faPlus,
  faRectangleList,
  faRightFromBracket,
  faRightToBracket,
  faStar,
  faTrashCan,
  faTrophy,
  faUser,
  faUserGroup,
  faUserPlus,
  faUserSlash,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

/**
 * The project's icon set: every icon the UI uses, named for what it means rather than for
 * the glyph. A screen imports `Icon` and passes one of these names, so the icon library
 * stays behind this module and the bundle only carries the icons listed here.
 *
 * A new screen that needs an icon adds it to this map first.
 */
export const ICONS = {
  add: faPlus,
  back: faArrowLeft,
  block: faBan,
  chat: faComment,
  check: faCheck,
  chevronDown: faChevronDown,
  chevronRight: faChevronRight,
  close: faXmark,
  copy: faCopy,
  disconnected: faLinkSlash,
  droplet: faDroplet,
  email: faEnvelope,
  flag: faFlag,
  forward: faArrowRight,
  game: faGamepad,
  history: faClockRotateLeft,
  home: faHouse,
  hint: faLightbulb,
  host: faCrown,
  key: faKey,
  leave: faDoorOpen,
  lock: faLock,
  login: faRightToBracket,
  logout: faRightFromBracket,
  password: faEye,
  passwordHidden: faEyeSlash,
  players: faUserGroup,
  playersOff: faUserSlash,
  profile: faUser,
  remove: faMinus,
  rules: faRectangleList,
  search: faMagnifyingGlass,
  send: faPaperPlane,
  settings: faGear,
  start: faPlay,
  streak: faFire,
  team: faPeopleGroup,
  star: faStar,
  smile: faFaceSmile,
  timer: faClock,
  trash: faTrashCan,
  trophy: faTrophy,
  userAdd: faUserPlus,
  warning: faExclamation,
  zoomIn: faMagnifyingGlassPlus,
  zoomOut: faMagnifyingGlassMinus,
} satisfies Record<string, IconDefinition>;

export type IconName = keyof typeof ICONS;
